package com.dannyk.toolbox.ui.screens.tools.files

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Clear
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Download
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.navigation.NavHostController
import com.dannyk.toolbox.ui.components.ToolScreenLayout
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.io.InputStream
import androidx.compose.ui.graphics.Color

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ImageToPDFScreen(navController: NavHostController) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    
    var selectedImages by remember { mutableStateOf<List<Uri>>(emptyList()) }
    var imageBitmaps by remember { mutableStateOf<List<Pair<Uri, Bitmap>>>(emptyList()) }
    
    // PDF Options
    var pageSize by remember { mutableStateOf("A4") }
    var orientation by remember { mutableStateOf("Portrait") }
    var marginSize by remember { mutableStateOf("Medium") }
    var isProcessing by remember { mutableStateOf(false) }
    var pdfGenerated by remember { mutableStateOf<File?>(null) }
    var showSuccessMessage by remember { mutableStateOf<String?>(null) }

    val imagePickerLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetMultipleContent()
    ) { uris: List<Uri> ->
        if (uris.isNotEmpty()) {
            selectedImages = uris
            scope.launch {
                val bitmaps = uris.mapNotNull { uri ->
                    try {
                        val inputStream: InputStream? = context.contentResolver.openInputStream(uri)
                        val bitmap = BitmapFactory.decodeStream(inputStream)
                        inputStream?.close()
                        if (bitmap != null) uri to bitmap else null
                    } catch (e: Exception) {
                        null
                    }
                }
                imageBitmaps = bitmaps
            }
        }
    }

    ToolScreenLayout(
        title = "Image to PDF",
        navController = navController
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Image Selection Section
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        text = "Select Images",
                        style = MaterialTheme.typography.titleMedium,
                        color = MaterialTheme.colorScheme.primary
                    )
                    
                    Spacer(modifier = Modifier.height(8.dp))
                    
                    Button(
                        onClick = { imagePickerLauncher.launch("image/*") },
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Icon(Icons.Default.Add, contentDescription = null)
                        Spacer(modifier = Modifier.width(8.dp))
                        Text("Choose Images")
                    }
                    
                    Spacer(modifier = Modifier.height(12.dp))
                    
                    if (selectedImages.isEmpty()) {
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(120.dp)
                                .border(
                                    width = 2.dp,
                                    color = MaterialTheme.colorScheme.outline.copy(alpha = 0.5f),
                                    shape = RoundedCornerShape(8.dp)
                                ),
                            contentAlignment = Alignment.Center
                        ) {
                            Text(
                                text = "No images selected\nTap button above to select",
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                                modifier = Modifier.align(Alignment.Center)
                            )
                        }
                    } else {
                        LazyRow(
                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            items(imageBitmaps) { (uri, bitmap) ->
                                Box {
                                    Image(
                                        bitmap = bitmap.asImageBitmap(),
                                        contentDescription = null,
                                        modifier = Modifier
                                            .width(100.dp)
                                            .height(100.dp)
                                            .border(
                                                width = 1.dp,
                                                color = MaterialTheme.colorScheme.outline,
                                                shape = RoundedCornerShape(4.dp)
                                            )
                                    )
                                    IconButton(
                                        onClick = {
                                            selectedImages = selectedImages.filter { it != uri }
                                            imageBitmaps = imageBitmaps.filter { it.first != uri }
                                        },
                                        modifier = Modifier
                                            .align(Alignment.TopEnd)
                                            .size(24.dp)
                                    ) {
                                        Icon(
                                            Icons.Default.Clear,
                                            contentDescription = "Remove",
                                            tint = MaterialTheme.colorScheme.error,
                                            modifier = Modifier.size(16.dp)
                                        )
                                    }
                                }
                            }
                        }
                        
                        Spacer(modifier = Modifier.height(4.dp))
                        
                        Text(
                            text = "${selectedImages.size} image(s) selected",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }

            // Page Size Selection
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        text = "Page Size",
                        style = MaterialTheme.typography.titleMedium,
                        color = MaterialTheme.colorScheme.primary
                    )
                    
                    Spacer(modifier = Modifier.height(8.dp))
                    
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        listOf("A4", "Letter", "Fit Image").forEach { size ->
                            FilterChip(
                                selected = pageSize == size,
                                onClick = { pageSize = size },
                                label = { Text(size) },
                                modifier = Modifier.weight(1f)
                            )
                        }
                    }
                }
            }

            // Orientation Selection
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        text = "Orientation",
                        style = MaterialTheme.typography.titleMedium,
                        color = MaterialTheme.colorScheme.primary
                    )
                    
                    Spacer(modifier = Modifier.height(8.dp))
                    
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        listOf("Portrait", "Landscape").forEach { orient ->
                            FilterChip(
                                selected = orientation == orient,
                                onClick = { orientation = orient },
                                label = { Text(orient) },
                                modifier = Modifier.weight(1f)
                            )
                        }
                    }
                }
            }

            // Margin Settings
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        text = "Margins",
                        style = MaterialTheme.typography.titleMedium,
                        color = MaterialTheme.colorScheme.primary
                    )
                    
                    Spacer(modifier = Modifier.height(8.dp))
                    
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        listOf("None", "Small", "Medium", "Large").forEach { margin ->
                            FilterChip(
                                selected = marginSize == margin,
                                onClick = { marginSize = margin },
                                label = { Text(margin) },
                                modifier = Modifier.weight(1f)
                            )
                        }
                    }
                }
            }

            // Generate Button
            Button(
                onClick = {
                    if (selectedImages.isEmpty()) {
                        Toast.makeText(context, "Please select at least one image", Toast.LENGTH_SHORT).show()
                        return@Button
                    }
                    
                    isProcessing = true
                    pdfGenerated = null
                    
                    scope.launch {
                        try {
                            val pdfFile = generatePdfFromImages(
                                context = context,
                                imageUris = selectedImages,
                                pageSize = pageSize,
                                orientation = orientation,
                                marginSize = marginSize
                            )
                            
                            withContext(Dispatchers.Main) {
                                pdfGenerated = pdfFile
                                isProcessing = false
                                showSuccessMessage = "PDF generated successfully!"
                                
                                Toast.makeText(context, "PDF saved to Downloads", Toast.LENGTH_LONG).show()
                            }
                        } catch (e: Exception) {
                            withContext(Dispatchers.Main) {
                                isProcessing = false
                                Toast.makeText(context, "Error generating PDF: ${e.message}", Toast.LENGTH_LONG).show()
                            }
                        }
                    }
                },
                enabled = selectedImages.isNotEmpty() && !isProcessing,
                modifier = Modifier.fillMaxWidth()
            ) {
                if (isProcessing) {
                    CircularProgressIndicator(
                        modifier = Modifier.size(20.dp),
                        strokeWidth = 2.dp,
                        color = MaterialTheme.colorScheme.onPrimary
                    )
                } else {
                    Icon(Icons.Default.Download, contentDescription = null)
                }
                Spacer(modifier = Modifier.width(8.dp))
                Text(if (isProcessing) "Generating..." else "Generate PDF")
            }

            // Success Message / Result Info
            showSuccessMessage?.let { message ->
                Card(
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primaryContainer),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(16.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            text = message,
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onPrimaryContainer,
                            modifier = Modifier.weight(1f)
                        )
                        pdfGenerated?.let { file ->
                            TextButton(onClick = {
                                showSuccessMessage = null
                                pdfGenerated = null
                            }) {
                                Text("Dismiss")
                            }
                        }
                    }
                }
            }

            // Instructions
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        text = "How to use:",
                        style = MaterialTheme.typography.titleSmall,
                        color = MaterialTheme.colorScheme.primary
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(
                        text = "• Select one or more images from your device\n" +
                               "• Choose page size (A4, Letter, or fit to image)\n" +
                               "• Select orientation (Portrait or Landscape)\n" +
                               "• Set margin size for the pages\n" +
                               "• Tap 'Generate PDF' to create your document\n" +
                               "• The PDF will be saved in your Downloads folder",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
        }
    }
}

private suspend fun generatePdfFromImages(
    context: Context,
    imageUris: List<Uri>,
    pageSize: String,
    orientation: String,
    marginSize: String
): File = withContext(Dispatchers.IO) {
    val pdfDocument = PdfDocument()
    
    // Determine page dimensions based on settings
    val margins = when (marginSize) {
        "None" -> 0
        "Small" -> 18
        "Medium" -> 36
        "Large" -> 72
        else -> 36
    }
    
    val pageInfoList = mutableListOf<PdfDocument.PageInfo>()
    val bitmapList = mutableListOf<Bitmap>()
    
    for (uri in imageUris) {
        try {
            val inputStream: InputStream? = context.contentResolver.openInputStream(uri)
            val originalBitmap = BitmapFactory.decodeStream(inputStream)
            inputStream?.close()
            
            if (originalBitmap != null) {
                val (pageWidth, pageHeight, scaledBitmap) = calculatePageDimensions(
                    originalBitmap = originalBitmap,
                    pageSize = pageSize,
                    orientation = orientation,
                    margins = margins
                )
                
                val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, bitmapList.size).create()
                pageInfoList.add(pageInfo)
                bitmapList.add(scaledBitmap)
            }
        } catch (e: Exception) {
            // Skip problematic images
        }
    }
    
    // Create pages and draw bitmaps
    for (i in bitmapList.indices) {
        val page = pdfDocument.startPage(pageInfoList[i])
        val canvas = page.canvas
        
        val bitmap = bitmapList[i]
        
        // Calculate position to center image on page
        val left = (pageInfoList[i].pageWidth - bitmap.width) / 2f
        val top = (pageInfoList[i].pageHeight - bitmap.height) / 2f
        
        canvas.drawBitmap(bitmap, left.toFloat(), top.toFloat(), null)
        pdfDocument.finishPage(page)
        
        if (bitmap != bitmapList[i] && !bitmap.isRecycled) {
            bitmap.recycle()
        }
    }
    
    // Save PDF file
    val downloadsDir = android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS)
    val outputFile = File(downloadsDir, "images_${System.currentTimeMillis()}.pdf")
    
    FileOutputStream(outputFile).use { outputStream ->
        pdfDocument.writeTo(outputStream)
    }
    
    pdfDocument.close()
    
    outputFile
}

private fun calculatePageDimensions(
    originalBitmap: Bitmap,
    pageSize: String,
    orientation: String,
    margins: Int
): Triple<Int, Int, Bitmap> {
    val density = 72f // PDF points per inch
    
    // Standard page sizes in points
    val a4Width = 595 // 210mm
    val a4Height = 842 // 297mm
    val letterWidth = 612 // 8.5in
    val letterHeight = 792 // 11in
    
    var pageWidth: Int
    var pageHeight: Int
    
    when (pageSize) {
        "Fit Image" -> {
            // Use image dimensions as base
            pageWidth = originalBitmap.width
            pageHeight = originalBitmap.height
            
            // Apply landscape if needed
            if (orientation == "Landscape" && pageWidth < pageHeight) {
                pageWidth = pageHeight.also { pageHeight = pageWidth }
            }
            
            return Triple(pageWidth, pageHeight, originalBitmap)
        }
        "Letter" -> {
            pageWidth = letterWidth
            pageHeight = letterHeight
        }
        else -> { // A4
            pageWidth = a4Width
            pageHeight = a4Height
        }
    }
    
    // Swap for landscape
    if (orientation == "Landscape") {
        pageWidth = pageHeight.also { pageHeight = pageWidth }
    }
    
    // Calculate available area after margins
    val availableWidth = pageWidth - (margins * 2)
    val availableHeight = pageHeight - (margins * 2)
    
    // Scale bitmap to fit within available area while maintaining aspect ratio
    val scale = minOf(
        availableWidth.toFloat() / originalBitmap.width,
        availableHeight.toFloat() / originalBitmap.height,
        1f // Don't upscale
    )
    
    val scaledWidth = (originalBitmap.width * scale).toInt()
    val scaledHeight = (originalBitmap.height * scale).toInt()
    
    val scaledBitmap = if (scale < 1f) {
        Bitmap.createScaledBitmap(originalBitmap, scaledWidth, scaledHeight, true)
    } else {
        originalBitmap
    }
    
    return Triple(pageWidth, pageHeight, scaledBitmap)
}
